<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EasyPatcher</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net45</TargetFramework>
    <Prefer32Bit>true</Prefer32Bit>
    <LangVersion>latest</LangVersion>
    <AppConfig>app.config</AppConfig>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <ProjectReference Include="../MagesLib/MagesLib.csproj" />
    <Reference Include="fastJSON">
      <HintPath>../../fastJSON.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
  </ItemGroup>
</Project>
